version: 2

project_name: jot

env:
  # Use Go 1.21 (from go.mod)
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - id: linux-amd64
    main: ./main.go
    binary: jot
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/zenobi-us/jot/cmd.Version={{.Version}}
      - -X github.com/zenobi-us/jot/cmd.Commit={{.Commit}}
      - -X github.com/zenobi-us/jot/cmd.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    files:
      - README.md
      - LICENSE

changelog:
  use: github-native
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  # Publish to GitHub Releases
  github:
    owner: zenobi-us
    name: opennotes

  prerelease: auto # Auto-detect prerelease from tag (rc, alpha, beta, etc.)
  mode: keep-existing # Don't overwrite existing
  draft: false
  footer: |
    ## SHA256 Checksums

    ```
    {{ .Checksums }}
    ```

    **Installation:**

    - **macOS (ARM64)**: `curl -sSL https://github.com/zenobi-us/jot/releases/download/{{ .Tag }}/jot_{{ .Version }}_Darwin_arm64.tar.gz | tar xz && sudo mv jot /usr/local/bin/`
    - **macOS (Intel)**: `curl -sSL https://github.com/zenobi-us/jot/releases/download/{{ .Tag }}/jot_{{ .Version }}_Darwin_x86_64.tar.gz | tar xz && sudo mv jot /usr/local/bin/`
    - **Linux (x86_64)**: `curl -sSL https://github.com/zenobi-us/jot/releases/download/{{ .Tag }}/jot_{{ .Version }}_Linux_x86_64.tar.gz | tar xz && sudo mv jot /usr/local/bin/`
    - **Linux (ARM64)**: `curl -sSL https://github.com/zenobi-us/jot/releases/download/{{ .Tag }}/jot_{{ .Version }}_Linux_arm64.tar.gz | tar xz && sudo mv jot /usr/local/bin/`
    - **Windows**: Download the `.zip` file from the release page

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
