#!/usr/bin/env bash
#MISE description="Run all tests"
#MISE env={ LOG_LEVEL = "error" }

set -e

echo "Starting CI Tests..."

mise container run "./Containerfile" "localhost/opennotes" "$pwd" "mise checks"

echo "CI Tests completed successfully."
