#!/usr/bin/env bash
#MISE description="Run ESLint"
#MISE usage="[OPTIONS]"
#MISE arg="fix:bool:Automatically fix problems:f"

FIX_FLAG=""
if [ "${fix}" = "true" ]; then
  FIX_FLAG="--fix"
fi

eslint . --ext .ts ${FIX_FLAG}