#!/usr/bin/env bash
#MISE description="Publish to npm registry"
#MISE depends=["setup"]
#USAGE flag "-t --tag <tag>" "Tag to publish with" default="latest"

set -e

function pre_release() {
	echo "No prereleass builds. Use go install https://this.repo@latest instead."
}

# For 'latest' tag, just do a normal release
function prod_release() {
	echo "Publishing to GitHub Releases"
	echo " > with tag: ${usage_tag}..."

	goreleaser release --clean

	echo "Published successfully!"
}

# Publish release to GitHub with GoReleaser

if [ "${usage_tag}" = "next" ]; then
	pre_release
else
	prod_release
fi
